{% set version = "0.6.7" %}

package:
  name: libgpuarray
  version: {{ version }}

source:
  fn: libgpuarray-{{ version }}.tar.gz
  url: https://github.com/Theano/libgpuarray/archive/v{{ version }}.tar.gz
  sha256: 5d3d6f54e53ffe1a43ca86329cf3e5b8b8c1b412cf222df092d741a4de212c2e
  patches:
    #########################################################
    # Workaround missing inline in VC 2008                  #
    #                                                       #
    # xref: https://github.com/Theano/libgpuarray/pull/460  #
    #########################################################
    - PR_460.diff

build:
  number: 0
  skip: true  # [win and py35]
  features:
    - vc9     # [win and py27]
    - vc10    # [win and py34]
    - vc14    # [win and py35]
    - vc14    # [win and py36]

requirements:
  build:
    - toolchain
    - python     # [win]
    - cmake

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}                      # [win]
  commands:
    - test -f ${PREFIX}/lib/libgpuarray.dylib                   # [osx]
    - test -f ${PREFIX}/lib/libgpuarray.so                      # [linux]
    - if not exist %PREFIX%\\Library\\lib\\gpuarray.lib exit 1  # [win]

about:
  home: http://github.com/Theano/libgpuarray
  license: ISC
  license_file: LICENSE
  summary: 'Library to manipulate arrays on GPU'
  doc_url: http://deeplearning.net/software/libgpuarray/
  dev_url: http://github.com/Theano/libgpuarray

extra:
  recipe-maintainers:
    - abergeron
