travis:
  secure:
    BINSTAR_TOKEN: gMgXfSASwyOPmS/f/nkpVPTVL/0KOp5n5lAEDp0+0AYz8OS5WP/Sll1NkvPdZZGZUzr9VhV+T0wwL+RPMIgDsKvB/9eHCgB/sJQ1swEhSaaMEQFq2/MVEgyy0Z8L12cFbZKMfLLIWJEQLc24vNQ3zIx27uuYbp15m9j0EPES1kbk1ykrNW/SnQ5TLtwfGOF2tHPhsb5XLCgxm32Y74PqS2vQnOyvKRfaVgnyJJh8Y/CIPl2WzudWYmCd/LzXOMLKKAaNW8MU978JqtBubfNLQK2nI/dxNKd9AqappPWjwbXQF3OC9edHvgC/H32uh+no+z6cT6ctGTRdXFOpfKAds+2cipaRBlOGSMjIBrqz/nm41r1e9o1fXubT5sRA/3oSxObfFMoyape7Lko1XAGh3eT0TZz/xZVtX7bfABAiayborKHBSLZCLklilZgobBTRuw64AkD+BmhkISQ4uLLtbFoTdEf1PtVr6/onY21RBwvDBEHaFoNU+B0j7NxVjcoThFTcITyUZVI4tmxm8DbUFUXrW9hzLGcolfSFej5SbQngOh7Xozq+i+f2lJxWZN+UOPqu2WgY+haY9boxRsGCAZYnVqHXS4gq8ep8quQIdlvixlE0RoaiMtPVpvBu///q3Yg7Kr/o6h3MvkzB3jwgxJKoOeeh3Fa0F30HsC421wU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
